name: Build

on:
  workflow_dispatch:

  push:
    branches: [ "main", "develop", "feature/**", "fix/**", "refactor/**" ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        #repository: https://github.com/victorsilvaTR/cicd_vb6
        path: 'C:\actions-runner-vb6\_work\cicd_vb6\cicd_vb6'

    - name: Build
      run: |
        cd C:\actions-runner-vb6\_work\cicd_vb6\cicd_vb6
        & "C:\Program Files (x86)\Microsoft Visual Studio\VB98\VB6.EXE" /make "Project1.vbp" /out "log.txt"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: build-artifact
        path: C:\actions-runner-vb6\_work\cicd_vb6\cicd_vb6\Project1.exe

        
